services:
  - type: web
    name: market-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: worker
    name: market-monitor-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python market_monitor_full.py
    plan: free
